PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS refund_events;
DROP TABLE IF EXISTS tool_events;
DROP TABLE IF EXISTS challenge_progress;
DROP TABLE IF EXISTS approvals;
DROP TABLE IF EXISTS internal_notes;
DROP TABLE IF EXISTS support_tickets;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, role TEXT NOT NULL);
CREATE TABLE orders (id TEXT PRIMARY KEY, user_id INTEGER REFERENCES users(id), item TEXT, amount INTEGER, status TEXT, refunded INTEGER DEFAULT 0);
CREATE TABLE support_tickets (id INTEGER PRIMARY KEY, created_by INTEGER REFERENCES users(id), subject TEXT, message TEXT, is_malicious INTEGER DEFAULT 0);
CREATE TABLE internal_notes (id INTEGER PRIMARY KEY, order_id TEXT REFERENCES orders(id), customer_visible_text TEXT, internal_metadata TEXT);
CREATE TABLE refund_events (id INTEGER PRIMARY KEY, order_id TEXT REFERENCES orders(id), requested_by INTEGER, amount INTEGER, timestamp TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE challenge_progress (challenge_id INTEGER PRIMARY KEY, solved INTEGER DEFAULT 0, solved_at TEXT, hints_used INTEGER DEFAULT 0, evidence_json TEXT);
CREATE TABLE tool_events (id INTEGER PRIMARY KEY, interaction_id TEXT, session_user INTEGER, user_prompt TEXT, mode TEXT, source TEXT, tool_name TEXT, arguments_json TEXT, authorization_result TEXT, tool_result TEXT, timestamp TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE approvals (id INTEGER PRIMARY KEY, requested_by INTEGER, order_id TEXT REFERENCES orders(id), amount INTEGER, status TEXT DEFAULT 'pending', timestamp TEXT DEFAULT CURRENT_TIMESTAMP);
DROP TABLE IF EXISTS lab_settings;
CREATE TABLE lab_settings (id INTEGER PRIMARY KEY CHECK (id = 1), mode TEXT NOT NULL);
INSERT INTO lab_settings VALUES (1, 'vulnerable');
